name: scoreboard_private
description: A public pacakge for communicating with Firebase Firestore.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^3.1.6
  fake_cloud_firestore: ^1.2.0
  scoreboard_public:
    path: ../scoreboard_public
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
